// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClicksByURLID = `-- name: CountClicksByURLID :one
SELECT COUNT(*) AS total
FROM clicks
WHERE url_id = $1
`

func (q *Queries) CountClicksByURLID(ctx context.Context, urlID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByURLID, urlID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countClicksTodayByURLID = `-- name: CountClicksTodayByURLID :one
SELECT COUNT(*) AS total
FROM clicks
WHERE url_id = $1
  AND clicked_at >= CURRENT_DATE
`

func (q *Queries) CountClicksTodayByURLID(ctx context.Context, urlID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksTodayByURLID, urlID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createClick = `-- name: CreateClick :one
INSERT INTO clicks (
    url_id,
    ip_address,
    user_agent,
    referer
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, url_id, clicked_at, ip_address, user_agent, referer
`

type CreateClickParams struct {
	UrlID     int64       `json:"url_id"`
	IpAddress pgtype.Text `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
	Referer   pgtype.Text `json:"referer"`
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, createClick,
		arg.UrlID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.ClickedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
	)
	return i, err
}

const getClicksByURLIDGroupedByDay = `-- name: GetClicksByURLIDGroupedByDay :many
SELECT
    DATE(clicked_at) AS day,
    COUNT(*)         AS total
FROM clicks
WHERE url_id = $1
GROUP BY DATE(clicked_at)
ORDER BY day ASC
`

type GetClicksByURLIDGroupedByDayRow struct {
	Day   pgtype.Date `json:"day"`
	Total int64       `json:"total"`
}

func (q *Queries) GetClicksByURLIDGroupedByDay(ctx context.Context, urlID int64) ([]GetClicksByURLIDGroupedByDayRow, error) {
	rows, err := q.db.Query(ctx, getClicksByURLIDGroupedByDay, urlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClicksByURLIDGroupedByDayRow
	for rows.Next() {
		var i GetClicksByURLIDGroupedByDayRow
		if err := rows.Scan(&i.Day, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
