// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RevokeRefreshToken(ctx context.Context, token string) error
}

var _ Querier = (*Queries)(nil)
