// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    short_code,
    original_url,
    user_id,
    expires_at,
    max_clicks
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, short_code, original_url, user_id, is_active, expires_at, max_clicks, created_at, updated_at
`

type CreateURLParams struct {
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MaxClicks   pgtype.Int4        `json:"max_clicks"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.UserID,
		arg.ExpiresAt,
		arg.MaxClicks,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateURL = `-- name: DeactivateURL :exec
UPDATE urls
SET is_active = false,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateURL(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateURL, id)
	return err
}

const deleteExpiredURLs = `-- name: DeleteExpiredURLs :execrows
DELETE FROM urls
WHERE expires_at IS NOT NULL
AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredURLs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredURLs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, user_id, is_active, expires_at, max_clicks, created_at, updated_at
FROM urls
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLsByUserID = `-- name: GetURLsByUserID :many
SELECT id, short_code, original_url, user_id, is_active, expires_at, max_clicks, created_at, updated_at
FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetURLsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetURLsByUserID(ctx context.Context, arg GetURLsByUserIDParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, getURLsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.UserID,
			&i.IsActive,
			&i.ExpiresAt,
			&i.MaxClicks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET original_url = $2,
    expires_at    = $3,
    max_clicks    = $4,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, short_code, original_url, user_id, is_active, expires_at, max_clicks, created_at, updated_at
`

type UpdateURLParams struct {
	ID          int64              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MaxClicks   pgtype.Int4        `json:"max_clicks"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURL,
		arg.ID,
		arg.OriginalUrl,
		arg.ExpiresAt,
		arg.MaxClicks,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
